version: "2"

services:
  web:
    build: "."
    links:
      - "db:postgres"
      - "redis:redis"
    ports:
      - "8000:80"
    command: python manage.py runserver 0.0.0.0:80
    env_file: .env-local

  db:
    image: mdillon/postgis:9.4
    volumes:
      - ".:/app:rw"
    environment:
      POSTGRES_DB: db

  redis:
     image: aldryn/redis
     environment:
       PASSWORD: "mypass"
